-- Historical participant-data operation retired from public source.
-- Original bytes are preserved in the operator-only security archive.
-- Existing production rows are not changed. Do not replay legacy imports.
-- Use scripts/stage_roster.mjs for new source data; see SECURITY_REMEDIATION.md.
