-- Add the final 24 teams from the 2026-09-08 PDF and normalize credentials.
begin;

update public.teams set username=lower(regexp_replace(team_name,'[^a-zA-Z0-9]','','g')), access_token=upper(regexp_replace(leader_name,'[^a-zA-Z0-9]','','g')), updated_at=now();

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0284','Team Titans','teamtitans','JEFFRIN S','','appuzx444@gmail.com','DHANALAKSHMI SRINIVASAN COLLEGE OF ENGINEERING COIMBATORE','ECE','Second Year','ORION-PS-04: Open Innovation Track','JEFFRINS','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'JEFFRIN S','Team Titans','','appuzx444@gmail.com','ECE','Second Year' from public.teams where registration_id='ORION-S0284' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'ASHWIN C S','Team Titans','','','ECE','Second Year' from public.teams where registration_id='ORION-S0284' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'AJAY KUMAR S','Team Titans','','','ECE','Second Year' from public.teams where registration_id='ORION-S0284' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'KALEESWARAN M','Team Titans','','','ECE','Second Year' from public.teams where registration_id='ORION-S0284' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0284','JEFFRIN S','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0284' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0285','X','x','K.S.Lakshman Kumar','','lakshmankumar2406@gmail.com','VELS university','BSC(AI&DS)','Second Year','ORION-PS-03: SYLVASENSE','KSLAKSHMANKUMAR','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'K.S.Lakshman Kumar','X','','lakshmankumar2406@gmail.com','BSC(AI&DS)','Second Year' from public.teams where registration_id='ORION-S0285' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Ambati Teja Venkat','X','','','BSC(AI&DS)','Second Year' from public.teams where registration_id='ORION-S0285' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'SaMi.JEEVA','X','','','BSC(AI&DS)','Second Year' from public.teams where registration_id='ORION-S0285' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Harishmen S','X','','','BSC(AI&DS)','Second Year' from public.teams where registration_id='ORION-S0285' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'SRI BALAJI E','X','','','BSC(AI&DS)','Second Year' from public.teams where registration_id='ORION-S0285' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'ARAVIND.P','X','','','BSC(AI&DS)','Second Year' from public.teams where registration_id='ORION-S0285' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0285','K.S.Lakshman Kumar','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0285' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0286','Quantum quorum','quantumquorum','Nithesh R','','nitheshpec@gmail.com','Panimalar engineering college','IT','Third Year','ORION-PS-04: Open Innovation Track','NITHESHR','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Nithesh R','Quantum quorum','','nitheshpec@gmail.com','IT','Third Year' from public.teams where registration_id='ORION-S0286' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Divya darshnee G','Quantum quorum','','','IT','Third Year' from public.teams where registration_id='ORION-S0286' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Navin Kumar V','Quantum quorum','','','IT','Third Year' from public.teams where registration_id='ORION-S0286' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Lalitha priyan CK','Quantum quorum','','','IT','Third Year' from public.teams where registration_id='ORION-S0286' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Thaarani S','Quantum quorum','','','IT','Third Year' from public.teams where registration_id='ORION-S0286' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'Krithik shankar','Quantum quorum','','','IT','Third Year' from public.teams where registration_id='ORION-S0286' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0286','Nithesh R','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0286' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0287','NEURO TRIX','neurotrix','Manoj M','','manojmurugesan1980@gmail.com','Sri Shakthi Institute of engineering and technology, Coimbatore','AIML','Second Year','ORION-PS-01: FLOATCHAT','MANOJM','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Manoj M','NEURO TRIX','','manojmurugesan1980@gmail.com','AIML','Second Year' from public.teams where registration_id='ORION-S0287' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'MADHANKUMAR K','NEURO TRIX','','','AIML','Second Year' from public.teams where registration_id='ORION-S0287' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Nikilesh kumar S S','NEURO TRIX','','','AIML','Second Year' from public.teams where registration_id='ORION-S0287' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Mukesh K','NEURO TRIX','','','AIML','Second Year' from public.teams where registration_id='ORION-S0287' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Vishnu D','NEURO TRIX','','','AIML','Second Year' from public.teams where registration_id='ORION-S0287' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'Prajeeth R','NEURO TRIX','','','AIML','Second Year' from public.teams where registration_id='ORION-S0287' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0287','Manoj M','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0287' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0288','ENJOY THE PRESSURE','enjoythepressure','SRIKUMARAN R S','','srikumaranrs14@gmail.com','MAHENDRA INSTITUTE OF TECHNOLOGY','BE ECE','Second Year','ORION-PS-04: Open Innovation Track','SRIKUMARANRS','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'SRIKUMARAN R S','ENJOY THE PRESSURE','','srikumaranrs14@gmail.com','BE ECE','Second Year' from public.teams where registration_id='ORION-S0288' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'SIGIN A','ENJOY THE PRESSURE','','','BE ECE','Second Year' from public.teams where registration_id='ORION-S0288' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'SURENDHAR K A','ENJOY THE PRESSURE','','','BE ECE','Second Year' from public.teams where registration_id='ORION-S0288' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'SANDHIYA V','ENJOY THE PRESSURE','','','BE ECE','Second Year' from public.teams where registration_id='ORION-S0288' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'SARANI A','ENJOY THE PRESSURE','','','BE ECE','Second Year' from public.teams where registration_id='ORION-S0288' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'PRIYADHIRISHINI M','ENJOY THE PRESSURE','','','BE ECE','Second Year' from public.teams where registration_id='ORION-S0288' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0288','SRIKUMARAN R S','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0288' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0289','Hacksprint','hacksprint','Rithanya Saravanan','','rithanyasaravanan18@gmail.com','Bannari Amman Institute of Technology','CSE','Second Year','ORION-PS-04: Open Innovation Track','RITHANYASARAVANAN','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Rithanya Saravanan','Hacksprint','','rithanyasaravanan18@gmail.com','CSE','Second Year' from public.teams where registration_id='ORION-S0289' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'DEVAMITHRA R G','Hacksprint','','','CSE','Second Year' from public.teams where registration_id='ORION-S0289' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'HASHINI O S','Hacksprint','','','CSE','Second Year' from public.teams where registration_id='ORION-S0289' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'ROHINI S','Hacksprint','','','CSE','Second Year' from public.teams where registration_id='ORION-S0289' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0289','Rithanya Saravanan','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0289' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0290','Fsociety','fsociety','Prasanna B','','prasanna2009126@gmail.com','Sathyabama University','BE CSE','First Year','ORION-PS-01: FLOATCHAT','PRASANNAB','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Prasanna B','Fsociety','','prasanna2009126@gmail.com','BE CSE','First Year' from public.teams where registration_id='ORION-S0290' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Ajmath R K','Fsociety','','','BE CSE','First Year' from public.teams where registration_id='ORION-S0290' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0290','Prasanna B','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0290' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0291','InnovateX','innovatex','Kishor J J','','kishorjj05@gmail.com','Jerusalem College of Engineering','CSE','Fourth Year','ORION-PS-04: Open Innovation Track','KISHORJJ','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Kishor J J','InnovateX','','kishorjj05@gmail.com','CSE','Fourth Year' from public.teams where registration_id='ORION-S0291' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Madhumitha C','InnovateX','','','CSE','Fourth Year' from public.teams where registration_id='ORION-S0291' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Harini K','InnovateX','','','CSE','Fourth Year' from public.teams where registration_id='ORION-S0291' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Aiswarya P','InnovateX','','','CSE','Fourth Year' from public.teams where registration_id='ORION-S0291' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Ezhilarasi C','InnovateX','','','CSE','Fourth Year' from public.teams where registration_id='ORION-S0291' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0291','Kishor J J','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0291' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0292','DEEPVERSE','deepverse','MONIKA D','','monikadevanathan2007@gmail.com','Anand institution of higher technology','BE- CSE','Third Year','ORION-PS-01: FLOATCHAT','MONIKAD','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'MONIKA D','DEEPVERSE','','monikadevanathan2007@gmail.com','BE- CSE','Third Year' from public.teams where registration_id='ORION-S0292' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'RAMYA BHUVANESHWARI K','DEEPVERSE','','','BE- CSE','Third Year' from public.teams where registration_id='ORION-S0292' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'MONI J K','DEEPVERSE','','','BE- CSE','Third Year' from public.teams where registration_id='ORION-S0292' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'PREM S','DEEPVERSE','','','BE- CSE','Third Year' from public.teams where registration_id='ORION-S0292' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'NAVEEN KUMAR A','DEEPVERSE','','','BE- CSE','Third Year' from public.teams where registration_id='ORION-S0292' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'VISHAL S','DEEPVERSE','','','BE- CSE','Third Year' from public.teams where registration_id='ORION-S0292' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0292','MONIKA D','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0292' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0293','Rapid current crew','rapidcurrentcrew','KiranKumar S','','kirankumar8015421877@gmail.com','SA Engineering college','BE.Electronic engineering (VLSI & DT)','Third Year','ORION-PS-04: Open Innovation Track','KIRANKUMARS','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'KiranKumar S','Rapid current crew','','kirankumar8015421877@gmail.com','BE.Electronic engineering (VLSI & DT)','Third Year' from public.teams where registration_id='ORION-S0293' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Bharath raj K','Rapid current crew','','','BE.Electronic engineering (VLSI & DT)','Third Year' from public.teams where registration_id='ORION-S0293' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'M Elanchezhiyan','Rapid current crew','','','BE.Electronic engineering (VLSI & DT)','Third Year' from public.teams where registration_id='ORION-S0293' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Sathish Kumar R','Rapid current crew','','','BE.Electronic engineering (VLSI & DT)','Third Year' from public.teams where registration_id='ORION-S0293' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Kavinitha K','Rapid current crew','','','BE.Electronic engineering (VLSI & DT)','Third Year' from public.teams where registration_id='ORION-S0293' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'Uma R','Rapid current crew','','','BE.Electronic engineering (VLSI & DT)','Third Year' from public.teams where registration_id='ORION-S0293' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0293','KiranKumar S','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0293' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0294','Phoenix','phoenix','Hariharan S','','hariharan11726@gmail.com','Dhaanish Chennai Engineering College','Computer Science and Business System','Second Year','ORION-PS-01: FLOATCHAT','HARIHARANS','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Hariharan S','Phoenix','','hariharan11726@gmail.com','Computer Science and Business System','Second Year' from public.teams where registration_id='ORION-S0294' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Janiish R','Phoenix','','','Computer Science and Business System','Second Year' from public.teams where registration_id='ORION-S0294' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Dani Joshua','Phoenix','','','Computer Science and Business System','Second Year' from public.teams where registration_id='ORION-S0294' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Akshara B','Phoenix','','','Computer Science and Business System','Second Year' from public.teams where registration_id='ORION-S0294' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Dharshana','Phoenix','','','Computer Science and Business System','Second Year' from public.teams where registration_id='ORION-S0294' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'Edward','Phoenix','','','Computer Science and Business System','Second Year' from public.teams where registration_id='ORION-S0294' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0294','Hariharan S','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0294' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0295','Success chaser','successchaser','Surendhar .S','','surendhar.2505150@srec.ac.in','Sri Ramakrishna engineering college','Information Technology','Second Year','ORION-PS-02: LEXVAULT','SURENDHARS','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Surendhar .S','Success chaser','','surendhar.2505150@srec.ac.in','Information Technology','Second Year' from public.teams where registration_id='ORION-S0295' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Prisha S','Success chaser','','','Information Technology','Second Year' from public.teams where registration_id='ORION-S0295' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Manimozhi R','Success chaser','','','Information Technology','Second Year' from public.teams where registration_id='ORION-S0295' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Pradikshina R','Success chaser','','','Information Technology','Second Year' from public.teams where registration_id='ORION-S0295' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Sakthi ganesh','Success chaser','','','Information Technology','Second Year' from public.teams where registration_id='ORION-S0295' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'Balakrishnan','Success chaser','','','Information Technology','Second Year' from public.teams where registration_id='ORION-S0295' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0295','Surendhar .S','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0295' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0296','AURA','aura','Mona','','mona.14032006@gmail.com','Easwari engineering college','Electronics and communication engineering','Third Year','ORION-PS-04: Open Innovation Track','MONA','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Mona','AURA','','mona.14032006@gmail.com','Electronics and communication engineering','Third Year' from public.teams where registration_id='ORION-S0296' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Lekha Shree S','AURA','','','Electronics and communication engineering','Third Year' from public.teams where registration_id='ORION-S0296' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Maya B Menon','AURA','','','Electronics and communication engineering','Third Year' from public.teams where registration_id='ORION-S0296' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Indu S','AURA','','','Electronics and communication engineering','Third Year' from public.teams where registration_id='ORION-S0296' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0296','Mona','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0296' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0297','MIDX','midx','S.ELAKKEYAA','','elakkeyaasasikumar@gmail.com','Hindusthan college of engineering','B.tech it','Second Year','ORION-PS-04: Open Innovation Track','SELAKKEYAA','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'S.ELAKKEYAA','MIDX','','elakkeyaasasikumar@gmail.com','B.tech it','Second Year' from public.teams where registration_id='ORION-S0297' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Yuvarani','MIDX','','','B.tech it','Second Year' from public.teams where registration_id='ORION-S0297' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0297','S.ELAKKEYAA','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0297' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0298','DankDuoCore','dankduocore','Pradeepa S N','','310624106149@eec.srmrmp.edu.in','SRM Easwari Engineering College','B.E. - Electronics and Communication Engineering','Third Year','ORION-PS-01: FLOATCHAT','PRADEEPASN','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Pradeepa S N','DankDuoCore','','310624106149@eec.srmrmp.edu.in','B.E. - Electronics and Communication Engineering','Third Year' from public.teams where registration_id='ORION-S0298' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Balamurugen S N','DankDuoCore','','','B.E. - Electronics and Communication Engineering','Third Year' from public.teams where registration_id='ORION-S0298' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0298','Pradeepa S N','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0298' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0299','TECHVERSE','techverse','M MOHAMMED UMAR','','mmohammedumar59@gmail.com','C ABDUL HAKEEM COLLEGE OF ENGINEERING AND TECHNOLOGY','BE COMPUTER SCIENCE AND ENGINEERING','Third Year','ORION-PS-04: Open Innovation Track','MMOHAMMEDUMAR','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'M MOHAMMED UMAR','TECHVERSE','','mmohammedumar59@gmail.com','BE COMPUTER SCIENCE AND ENGINEERING','Third Year' from public.teams where registration_id='ORION-S0299' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'MOHAMMED SALIK R','TECHVERSE','','','BE COMPUTER SCIENCE AND ENGINEERING','Third Year' from public.teams where registration_id='ORION-S0299' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'MOHAMMED SAYEED S','TECHVERSE','','','BE COMPUTER SCIENCE AND ENGINEERING','Third Year' from public.teams where registration_id='ORION-S0299' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'ZIA ANES M','TECHVERSE','','','BE COMPUTER SCIENCE AND ENGINEERING','Third Year' from public.teams where registration_id='ORION-S0299' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'RAKSHITHA B','TECHVERSE','','','BE COMPUTER SCIENCE AND ENGINEERING','Third Year' from public.teams where registration_id='ORION-S0299' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'THULASI S','TECHVERSE','','','BE COMPUTER SCIENCE AND ENGINEERING','Third Year' from public.teams where registration_id='ORION-S0299' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0299','M MOHAMMED UMAR','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0299' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0300','Tech Rockstars','techrockstars','S Varun Narayan','','varuns.181890@gmail.com','Meenakshi Sundararajan Engineering College Kodambakkam','CSE','Third Year','ORION-PS-02: LEXVAULT','SVARUNNARAYAN','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'S Varun Narayan','Tech Rockstars','','varuns.181890@gmail.com','CSE','Third Year' from public.teams where registration_id='ORION-S0300' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Shakthivel H','Tech Rockstars','','','CSE','Third Year' from public.teams where registration_id='ORION-S0300' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Mohammed Ayub S','Tech Rockstars','','','CSE','Third Year' from public.teams where registration_id='ORION-S0300' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Radha Krishnan R','Tech Rockstars','','','CSE','Third Year' from public.teams where registration_id='ORION-S0300' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0300','S Varun Narayan','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0300' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0301','core shift','coreshift','Rupavathy M','','rupavathymeikandamuthu@gmail.com','Easwari Engineering College','BE-ECE','Third Year','ORION-PS-04: Open Innovation Track','RUPAVATHYM','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Rupavathy M','core shift','','rupavathymeikandamuthu@gmail.com','BE-ECE','Third Year' from public.teams where registration_id='ORION-S0301' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Neha Neeta A','core shift','','','BE-ECE','Third Year' from public.teams where registration_id='ORION-S0301' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Pavithra K','core shift','','','BE-ECE','Third Year' from public.teams where registration_id='ORION-S0301' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Sai Keertana S','core shift','','','BE-ECE','Third Year' from public.teams where registration_id='ORION-S0301' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Sakthi SP','core shift','','','BE-ECE','Third Year' from public.teams where registration_id='ORION-S0301' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0301','Rupavathy M','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0301' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0302','Zynova','zynova','Samvridha D','','samvridha0@gmail.com','SRM Easwari engineering college','BE - Electronics and Communication engineering','Third Year','ORION-PS-01: FLOATCHAT','SAMVRIDHAD','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Samvridha D','Zynova','','samvridha0@gmail.com','BE - Electronics and Communication engineering','Third Year' from public.teams where registration_id='ORION-S0302' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Sancia Stephie NP','Zynova','','','BE - Electronics and Communication engineering','Third Year' from public.teams where registration_id='ORION-S0302' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Poornima Prabu','Zynova','','','BE - Electronics and Communication engineering','Third Year' from public.teams where registration_id='ORION-S0302' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Nisrin A','Zynova','','','BE - Electronics and Communication engineering','Third Year' from public.teams where registration_id='ORION-S0302' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Pragathi Prabu','Zynova','','','BE - Electronics and Communication engineering','Third Year' from public.teams where registration_id='ORION-S0302' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0302','Samvridha D','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0302' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0303','ByteForce','byteforce','Sri Thean Mathy','','sritheanmathy@gmail.com','Thiagarajar College of engineering','CSE','Second Year','ORION-PS-04: Open Innovation Track','SRITHEANMATHY','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Sri Thean Mathy','ByteForce','','sritheanmathy@gmail.com','CSE','Second Year' from public.teams where registration_id='ORION-S0303' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Sanjana C','ByteForce','','','CSE','Second Year' from public.teams where registration_id='ORION-S0303' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'KAVIN KUMAR AK','ByteForce','','','CSE','Second Year' from public.teams where registration_id='ORION-S0303' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0303','Sri Thean Mathy','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0303' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0304','INNOVATORS UNITED','innovatorsunited','Swetha Suresh','','swethasuresh1905@gmail.com','Dhanalakshmi College Of Engineering','B.tech Artificial Intelligence & Data Science','Fourth Year','ORION-PS-04: Open Innovation Track','SWETHASURESH','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Swetha Suresh','INNOVATORS UNITED','','swethasuresh1905@gmail.com','B.tech Artificial Intelligence & Data Science','Fourth Year' from public.teams where registration_id='ORION-S0304' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Venu Raghavan V','INNOVATORS UNITED','','','B.tech Artificial Intelligence & Data Science','Fourth Year' from public.teams where registration_id='ORION-S0304' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Prekshitha V','INNOVATORS UNITED','','','B.tech Artificial Intelligence & Data Science','Fourth Year' from public.teams where registration_id='ORION-S0304' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Shamini V','INNOVATORS UNITED','','','B.tech Artificial Intelligence & Data Science','Fourth Year' from public.teams where registration_id='ORION-S0304' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Pushparani B','INNOVATORS UNITED','','','B.tech Artificial Intelligence & Data Science','Fourth Year' from public.teams where registration_id='ORION-S0304' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'Rohith Venkatagiri','INNOVATORS UNITED','','','B.tech Artificial Intelligence & Data Science','Fourth Year' from public.teams where registration_id='ORION-S0304' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0304','Swetha Suresh','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0304' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0305','Synergy squad','synergysquad','ShreeShopika S.N','','shreeshopikasomasundaram22@gmail.com','Bannari Amman Institute of Technology, Sathy, Erode','CSE','Second Year','ORION-PS-04: Open Innovation Track','SHREESHOPIKASN','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'ShreeShopika S.N','Synergy squad','','shreeshopikasomasundaram22@gmail.com','CSE','Second Year' from public.teams where registration_id='ORION-S0305' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'E. Nika R.S','Synergy squad','','','CSE','Second Year' from public.teams where registration_id='ORION-S0305' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Dharunika R','Synergy squad','','','CSE','Second Year' from public.teams where registration_id='ORION-S0305' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0305','ShreeShopika S.N','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0305' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0306','CAGU','cagu','Priya dharshini saravanan','','priyadharshinisaravanan924@gmail.com','Sathyabama Institute of science and technology','BSC Data science','Second Year','ORION-PS-04: Open Innovation Track','PRIYADHARSHINISARAVANAN','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Priya dharshini saravanan','CAGU','','priyadharshinisaravanan924@gmail.com','BSC Data science','Second Year' from public.teams where registration_id='ORION-S0306' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Subashri Selvam','CAGU','','','BSC Data science','Second Year' from public.teams where registration_id='ORION-S0306' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Roshini nachiappan','CAGU','','','BSC Data science','Second Year' from public.teams where registration_id='ORION-S0306' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Hemavarthini A','CAGU','','','BSC Data science','Second Year' from public.teams where registration_id='ORION-S0306' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0306','Priya dharshini saravanan','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0306' on conflict (team_id) do nothing;

insert into public.teams (registration_id,team_name,username,leader_name,leader_phone,leader_email,institution,department,year,problem_statement,access_token,payment_status,amount,registration_status,round_1_status,round_2_status,admin_notes) values ('ORION-S0307','CodeNova','codenova','Poorva M','','poorvam24cs@psnacet.edu.in','PSNA COLLEGE OF ENGINEERING AND TECHNOLOGY','Computer science and engineering','Third Year','ORION-PS-04: Open Innovation Track','POORVAM','VERIFIED',100,'REGISTERED','SUBMISSION_OPEN','LOCKED','Official verified roster (2026-09-08)') on conflict (registration_id) do update set team_name=excluded.team_name,username=excluded.username,leader_name=excluded.leader_name,leader_email=excluded.leader_email,institution=excluded.institution,department=excluded.department,year=excluded.year,problem_statement=excluded.problem_statement,access_token=excluded.access_token,updated_at=now();
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,1,'Poorva M','CodeNova','','poorvam24cs@psnacet.edu.in','Computer science and engineering','Third Year' from public.teams where registration_id='ORION-S0307' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,2,'Ragavi T','CodeNova','','','Computer science and engineering','Third Year' from public.teams where registration_id='ORION-S0307' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,3,'Priyadharshini PG','CodeNova','','','Computer science and engineering','Third Year' from public.teams where registration_id='ORION-S0307' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,4,'Rajeswari M','CodeNova','','','Computer science and engineering','Third Year' from public.teams where registration_id='ORION-S0307' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,5,'Sailan RS','CodeNova','','','Computer science and engineering','Third Year' from public.teams where registration_id='ORION-S0307' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.team_members (team_id,member_number,member_name,team_name,member_phone,member_email,department,year) select id,6,'Ranesh S','CodeNova','','','Computer science and engineering','Third Year' from public.teams where registration_id='ORION-S0307' on conflict (team_id,member_number) do update set member_name=excluded.member_name,team_name=excluded.team_name,member_email=excluded.member_email,department=excluded.department,year=excluded.year;
insert into public.payments (team_id,utr_number,payer_name,payer_upi,amount,payment_status,notes,verified_at,verified_by) select id,'VERIFIED-ORION-S0307','Poorva M','official@upi',100,'VERIFIED','Official verified roster PDF import',now(),'system_pdf_importer' from public.teams where registration_id='ORION-S0307' on conflict (team_id) do nothing;

commit;
