-- ==============================================================================
-- 025 — Register ORION-S0308 … S0321, and fold HORIZON into S0287
-- ==============================================================================
--
-- 14 squads supplied as a tab-separated paste. 13 inserted; the 14th turned out
-- to be a squad already registered. Contact emails are not reproduced here —
-- this repository is public and they are participants' personal addresses.
--
-- Every squad went in leader-first: teams.leader_name only, with team_members
-- holding the OTHER members numbered from 1, per the contract set in 018/022.
-- Declared team size matched the names actually listed for all 13.
--
-- payment_status = VERIFIED, matching the existing roster. No payments rows are
-- created; there is no UTR or amount for these and inventing one would pollute
-- the ledger, same reasoning as migration 014.
--
-- username and access_token follow the standing convention and were left to
-- the trg_teams_username trigger and the leader-name slug respectively. No new
-- login collides with an existing one.
--
-- ── Two problems in the input, both resolved by the organisers ────────────────
--
-- 1. ORION-S0319 was used TWICE — "OG Girls" (Narra Charita Sree, Vignan) and
--    "fantastic-4" (Narasimman V, Nandha College). registration_id is UNIQUE so
--    both could not stand. OG Girls keeps S0319 as listed first; fantastic-4 was
--    given S0321, the next free id.
--
-- 2. ORION-S0311 "HORIZON" was the SAME squad as the existing ORION-S0287
--    "NEURO TRIX": same leader (Manoj M), same email, same five members, same
--    institution — only the team name differed. Rather than a second row giving
--    six people two logins, S0287 was renamed to HORIZON. The trg_teams_username
--    trigger re-derived its username from neurotrix to horizon, and
--    trg_teams_propagate_team_name pushed the new name across its roster.
--    THE LOGIN FOR THIS SQUAD HAS CHANGED — they must be told.
--    The S0311 paste also carried member emails S0287 had never had, so its five
--    roster rows were backfilled with those, plus department and year.
--
-- ── Left as given, flagged rather than guessed ────────────────────────────────
--
--   S0310  Thitiksha.V's address reads "...@rajalakshmi edu.in" — a space where
--          the dot belongs, so it is unusable as typed. The other two members of
--          the squad use @rajalakshmi.edu.in. Stored verbatim; a human should
--          confirm before it is corrected.
--   S0314  The leader (Ashutosh rout) and member 2 (Shailesh kumar rout) appear
--          to have swapped addresses: the leader's is "shaileshkumar334guts@".
--          Stored as submitted.
--   S0315  "Mohammed Gani S" was listed with no email, department or year.
--          member_phone is NOT NULL so it holds 'NOT_PROVIDED'; the rest is NULL.
--   S0320  The problem statement arrived as "ORION-PS-02: LEXVAULT trghis rtoo".
--          The trailing text is stray keystrokes and was dropped.
--
-- No phone numbers were supplied for any of the 14, so leader_phone and
-- member_phone hold 'NOT_PROVIDED'.
--
-- ── Result ───────────────────────────────────────────────────────────────────
--
--   teams        291 -> 304
--   team_members 1126 -> 1176
--   leader_email 289 -> 302 of 304
--   duplicate logins 0, blank credentials 0, leader-in-roster 0,
--   roster numbering gaps 0
--
-- The 13 new registrations, for the record:
--
--   S0308  ALITA           P.HRUDAY                     Vignan's Foundation
--   S0309  ElectronX       Koushik S                    KPR Institute
--   S0310  Orbit           Venmathi Ilavarasu           Rajalakshmi
--   S0312  ALGNITE         Kavipriya M                  Sri Eshwar
--   S0313  NEXORA43        M Aswin Muthaiya             Prathyusha
--   S0314  ASTRA X         Ashutosh rout                CV Raman Global
--   S0315  TensorTech      Shiva Sanjai                 Sri Manakula Vinayagar
--   S0316  TEAM IMPACT     Dravid Anand B               VIT Vellore
--   S0317  Synora          Muthu Yogeshwaran.V          Sathyabama
--   S0318  Fusion 5        Mohammed Ayyan Muyeenuddin   Sathyabama
--   S0319  OG Girls        Narra Charita Sree           Vignan
--   S0320  Gokulnath A     Gokulnath Nath A             Rathinam
--   S0321  fantastic-4     Narasimman V                 Nandha
--
-- Applied against the live database on 2026-09-08. Backups taken first:
-- _bak_teams_pre_s0308 and _bak_team_members_pre_s0308.
